name: Expo doctor

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  expo-doctor:
    runs-on: ubuntu-latest
    env:
      EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install expo-cli
        run: npm install expo-cli -g
      - name: Install dependencies
        run: npm ci
      - name: Run expo doctor
        run: npx expo-doctor
